# Generated by Django 5.2 on 2025-05-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='psychologist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='psychologists/'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
