# Generated by Django 5.2 on 2025-05-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0002_remove_psychologist_whatsapp_link_psychologist_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='specialization',
        ),
        migrations.AddField(
            model_name='psychologist',
            name='country',
            field=models.CharField(default='Казахстан', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
