# Generated by Django 5.1.6 on 2025-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_psychologistprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_psychologist',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='PsychologistProfile',
        ),
    ]
