# Generated by Django 5.2 on 2025-05-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_psychologytip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='psychologists/')),
                ('description', models.TextField()),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
    ]
